//输出下列代码name3的值分别是多少？并且把预解析的过程写出来
// var a = 25;
// var name3 = "zs";
// function f3() {
//     var name3 = "ls";
//     function f4() {
//         name3 = "ww";
//     }
//     f4();
//     console.log(name3);   // ?
// }
// f3();
// console.log(name3); // ?
// //--------------------------------------
// var a
// var a = 25;
// var name3
// name3 = "zs";
// function f3() {
//     var name3
//     var name3 = "ls";
//     function f4() {
//         name3 = "ww";
//     }
//     f4();
//     console.log(name3);   // ?WW
// }
// f3();
// console.log(name3); // ?ZS